language: cpp

sudo: required

dist: trusty

before_install:
  - sudo add-apt-repository -y ppa:edd/misc

install:
  - sudo apt-get install libboost-all-dev

compiler:
  - gcc

script:
  - make clean all
